package Pojo;
// Generated Jun 22, 2019 7:24:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private Integer invId;
     private Categories categories;
     private String invName;
     private String invDescription;
     private String invImage;
     private String invThumbnail;
     private BigDecimal invPrice;
     private short invStock;
     private short invSize;
     private short invWeight;
     private String invLocation;
     private String invVendor;
     private String invStyle;

    public Inventory() {
    }

    public Inventory(Categories categories, String invName, String invDescription, String invImage, String invThumbnail, BigDecimal invPrice, short invStock, short invSize, short invWeight, String invLocation, String invVendor, String invStyle) {
       this.categories = categories;
       this.invName = invName;
       this.invDescription = invDescription;
       this.invImage = invImage;
       this.invThumbnail = invThumbnail;
       this.invPrice = invPrice;
       this.invStock = invStock;
       this.invSize = invSize;
       this.invWeight = invWeight;
       this.invLocation = invLocation;
       this.invVendor = invVendor;
       this.invStyle = invStyle;
    }
   
    public Integer getInvId() {
        return this.invId;
    }
    
    public void setInvId(Integer invId) {
        this.invId = invId;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getInvName() {
        return this.invName;
    }
    
    public void setInvName(String invName) {
        this.invName = invName;
    }
    public String getInvDescription() {
        return this.invDescription;
    }
    
    public void setInvDescription(String invDescription) {
        this.invDescription = invDescription;
    }
    public String getInvImage() {
        return this.invImage;
    }
    
    public void setInvImage(String invImage) {
        this.invImage = invImage;
    }
    public String getInvThumbnail() {
        return this.invThumbnail;
    }
    
    public void setInvThumbnail(String invThumbnail) {
        this.invThumbnail = invThumbnail;
    }
    public BigDecimal getInvPrice() {
        return this.invPrice;
    }
    
    public void setInvPrice(BigDecimal invPrice) {
        this.invPrice = invPrice;
    }
    public short getInvStock() {
        return this.invStock;
    }
    
    public void setInvStock(short invStock) {
        this.invStock = invStock;
    }
    public short getInvSize() {
        return this.invSize;
    }
    
    public void setInvSize(short invSize) {
        this.invSize = invSize;
    }
    public short getInvWeight() {
        return this.invWeight;
    }
    
    public void setInvWeight(short invWeight) {
        this.invWeight = invWeight;
    }
    public String getInvLocation() {
        return this.invLocation;
    }
    
    public void setInvLocation(String invLocation) {
        this.invLocation = invLocation;
    }
    public String getInvVendor() {
        return this.invVendor;
    }
    
    public void setInvVendor(String invVendor) {
        this.invVendor = invVendor;
    }
    public String getInvStyle() {
        return this.invStyle;
    }
    
    public void setInvStyle(String invStyle) {
        this.invStyle = invStyle;
    }




}


